### ISSUE TITLE
Write firebase database validation rules for data

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#117]
Certain data needs certain structure. For example, calendar titles need to be strings, dates need to be dates ( currently they need to be strings but may need to change this ).

**Comment by johntyree** [comment]
I think you mean validation?

https://firebase.google.com/docs/database/security/#section-validation

**Comment by andrayantelo** [comment]
Yes, I mean validation.

**Comment by andrayantelo** [comment]
Do I want to save the user's email in the users/user.uid/ section of the database?
What does it mean to define database indices?

`"calendarState": {
    ".read" : "auth !== null",
     ".write" : "auth !== null && (!data.exists() || root.child('calendars/' +$calendarId + '/writers/' + auth.uid).exists())"
       },`

Why did `!newData.exists()` not work?
