### ISSUE TITLE
Firebase database permissions 

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#189]
firebase.database().ref('calendar/149270802040326980/calendarState').once('value').then(function(val) {console.log(val)});

I ran that in the console.

Permission was denied for this. The rules for reading data inside calendarState:

`"calendars":{
      "$calendarId": {
        "calendarState": {
          ".read" : "auth !== null && (!data.exists() || root.child('calendars/' + $calendarId + '/readers/' + auth.uid).exists())",
          ".write" : "auth !== null && (!data.exists() || root.child('calendars/' +$calendarId + '/writers/' + auth.uid).exists())",`

I was signed in, the calendarId is one of my calendars, I am a reader and writer for that calendarId.

@johntyree Do you see something I probably don't see? lol

**Comment by johntyree** [comment]
Looks like a typo in the query? `calendar/` -> `calendars/` ?

**Comment by andrayantelo** [comment]
sigh.. lol
