### ISSUE TITLE
Throwing away month objects or storing them?

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#3]
I have the function called getMonthStates, a method on the Calendar class.
It looks at the user input, the user provides a startDate, and they also provide how many years they want to track.
So if their startDate is Jan 1, 2017 and they want to track five years, 
this function, getMonthStates, will make an array of monthStates for  all of those months in that time period.
The way it does is by looping. It makes a month object, initializes a monthState for it (which is a Month object method) and then stores this monthState in an array, monthStates, which is returned at the end of getMonthStates.
The issue:
It makes a month object
does what it needs to do
and that's it for the month object, it basically gets thrown away.
is that even a good way to go about it?
later to make the actual calendar divs and everything, I'm going to need to use Month object methods
so should i be storing these month objects that i make inside of another array?

**Comment by johntyree** [comment]
It's fine to make the object and throw it away.  The only concern about this might be performance, but I'm very sure that you're nowhere near that yet. Maybe if you were making millions of these it would be worth revisiting. As it is, I'd say just makes a month object when you need one and give it the state you care about.
