### ISSUE TITLE
Move the delete button

### ISSUE THREAD

**Issue by andrayantelo** [andrayantelo/calendar-reboot#66]

**Comment by andrayantelo** [comment]
@johntyree So I was thinking maybe add a dropdown next to the saved calendars dropdown that is called "Actions", have "'Delete Calendar" in there, and maybe also "Undo Delete" ? Not sure what other actions would be in there. 

Or, put a delete calendar button next to the clear button in the build calendar form?

**Comment by johntyree** [comment]
When in doubt, copy someone else. Maybe check out how keep.google.com does it? Or some other service with little widgets on the page that you create and remove?

**Comment by andrayantelo** [comment]
It's basically a small dropdown with other options and delete is included in them. There are only so many things you can do with a calendar. Place a checkmark, remove a checkmark, and delete a calendar. That's it for now. I was thinking in the future one could maybe edit the title? And then of course I'd add the feature where you can add another month (or add another year). Any other actions you can think of?

**Comment by johntyree** [comment]
I could see maybe wanting to add a color scheme to a calendar, but that's about it right now. As far as non-superficial changes go, I think you've probably outlined them all. Edit the titles, edit the start / end date, delete the calendar.

Even if delete is the only option in the drop down, I think it still makes sense.
